version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abdo@example.com
      PGADMIN_DEFAULT_PASSWORD: abdo
    ports:
      - '5050:80'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: pgdb # Name of the database
      POSTGRES_USER: postgres # Database user
      POSTGRES_PASSWORD: postgres # Database password
    ports:
      - '5433:5432'
    volumes:
      - 'pgvector_data:/var/lib/postgresql/data'
    restart: unless-stopped
    labels:
      - "org.springframework.boot.service-connection=postgresql" # Corrected label for PostgreSQL

volumes:
  ollama_data:
  pgvector_data:
